routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});

Route::get('edad/{edad?}',function($edad='20'){
    return 'tu edad es de '.$edad;
});

Route::get('usuario/{codigo}',function($codigo){
    return 'hola usuario'.$codigo;
})->where('codigo','[0-9]+');

Route::get('controlador','PruebaController@index');
Route::get('name/{nombre?}','PruebaController@nombre');

Route::resource('movie','MovieController');*/

Route::get('/','FrontController@index');
Route::get('contacto','FrontController@contacto');
Route::resource('mail','MailController');
Route::get('reviews','FrontController@reviews');
Route::get('admin','FrontController@admin');

Route::resource('usuario','UsuarioController');
Route::get('towns/{id}','UsuarioController@getTowns');
Route::resource('genero','GeneroController');
Route::get('generos','GeneroController@listing');
Route::resource('pelicula','MovieController');

Route::resource('log','LogController');
Route::get('logout','LogController@logout');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/pelicula/create.blade.php
@extends('layouts.admin')

@section('content')
    {!!Form::open(['route'=>'pelicula.store','method'=>'POST','files'=>true])!!}
        <div id="msj-success" class="alert alert-success alert-dismissible" role="alert" style="display:none">
        <button type="button" class="close" data-dismiss="alert" data-label="Close"><span aria-hidden="true">&times;</span></button>  
        <strong>Pelicual Agregada Correctamente</strong>
        </div>

        <div id="msj-error" class="alert alert-danger alert-dismissible" role="alert" style="display:none">
            <button type="button" class="close" data-dismiss="alert" data-label="Close"><span aria-hidden="true">&times;</span></button>  
            <strong id="msj"></strong>
        </div>
        @include('pelicula.forms.peli')
        {!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
    {!!Form::close()!!}
@stop

resources/views/pelicula/edit.blade.php
@extends('layouts.admin')

@section('content')
    @include('alerts.request')
        {!!Form::model($movie,['route'=>['pelicula.update',$movie->id],'method'=>'PUT','files'=>true])!!}
        @include('pelicula.forms.peli')
        {!!Form::submit('Actualizar',['class'=>'btn btn-primary'])!!}
    {!!Form::close()!!}
    
    {!!Form::open(['route'=>['pelicula.destroy',$movie->id],'method'=>'DELETE'])!!}
        {!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
    {!!Form::close()!!}
@endsection

resources/views/pelicula/index.blade.php
@extends('layouts.admin')
    @include('alerts.success')
    @section('content')
        <table class="table">
            <thead>
                <th>Nombre</th>
                <th>Genero</th>
                <th>Direccion</th>
                <th>Caratula</th>
                <th>Operaciones</th>
            </thead>
            @foreach($movies as $movie)
            <tbody>
                <td>{{$movie->name}}</td>
                <td>{{$movie->genre}}</td>
                <td>{{$movie->direction}}</td>
                <td>
                    <img src="movies/{{$movie->path}}" alt="" style="width: 100px"/>
                </td>
                <td>{!!link_to_route('pelicula.edit',$title='Editar',$parameters=$movie->id,$attributes=['class'=>'btn btn-primary'])!!}</td>
            </tbody>
            @endforeach
        </table>
    @endsection